### ISSUE TITLE
Initialising CorpusAnalysis pipeline allocates too much memory

### ISSUE THREAD

**Issue by Snackya** [phHartl/eu-judgement-analyse#46]
When trying to call CorpusAnalysis.init_pipeline() on the entire corpus, `self.corpus = textacy.Corpus(self.nlp, data=texts)` allocates 12GB of memory within 1 minute.
This must absolutely be fixed if possible.

**Comment by phHartl** [comment]
Updated requirements to spacy 2.1.9 ( 56e3e36) which fixed the memory leak present in spacy 2.1.8.
