### ISSUE TITLE
Link to fulltext on EUR-Lex for single document queries

### ISSUE THREAD

**Issue by kappa4head** [phHartl/eu-judgement-analyse#64]
Full text can be found via CELEX number.

Example URL: https://eur-lex.europa.eu/legal-content/EN/TXT/?&uri=CELEX:61955CJ0008

**Comment by kappa4head** [comment]
Implemented in ce90957a528dd30bbf6cba356a598507dcc09604 .

Currently only works when the CELEX number is manually searched for. Still need access to celex number for any search result (eg. search for ECLI -> search result returns CELEX number as well).

**Comment by phHartl** [comment]
I suggest adding this feature for a whole corpus as well. We got all CELEX numbers for each document in the corpus anyways. You just need the updates from the API branch.
