### ISSUE TITLE
When requesting the whole corpus for a language an AttributeError occurres

### ISSUE THREAD

**Issue by phHartl** [phHartl/eu-judgement-analyse#69]
Exception has occurred: AttributeError:
'list' object has no attribute 'items'
File "request_parser.py", line 165, in parse_to_json
    for key, value in _temp_dict.items():
The problematic document: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A62009CJ0438&qid=1603385715363

**Comment by Snackya** [comment]
The issue seems to be another weird response, for the case_law_directory in this case.
This is what EUR-Lex returns:
```json
"CASE-LAW_IS_ABOUT_CONCEPT.MEMBERLIST": {
    "NESTEDLIST": null
}
```
Fix should be ready soon
